// <auto-generated />
using System;
using Damco.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Damco.Domain.Migrations
{
    [DbContext(typeof(DamcoContext))]
    [Migration("20210221090328_update_supplier_rate_21_02_2021_14_32")]
    partial class update_supplier_rate_21_02_2021_14_32
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Damco.Domain.Entites.damco_supplier", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("damco_supplier");
                });

            modelBuilder.Entity("Damco.Domain.Entites.damco_supplier_rate", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("fk_supplier_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<double>("rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("fk_supplier_id");

                    b.ToTable("damco_supplier_rate");
                });

            modelBuilder.Entity("Damco.Domain.Entites.damco_supplier_rate", b =>
                {
                    b.HasOne("Damco.Domain.Entites.damco_supplier", "damco_supplier")
                        .WithMany("damco_supplier_rates")
                        .HasForeignKey("fk_supplier_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("damco_supplier");
                });

            modelBuilder.Entity("Damco.Domain.Entites.damco_supplier", b =>
                {
                    b.Navigation("damco_supplier_rates");
                });
#pragma warning restore 612, 618
        }
    }
}
